FROM alpine
RUN apk add --no-cache --upgrade bash
RUN apk add jq
RUN apk add curl
RUN apk add zip
COPY build.sh .

ADD BP-BASE-SHELL-STEPS /opt/buildpiper/shell-functions/

ENV BUILD_NUMBER ""
ENV BUILD_COMPONENT_NAME ""
ENV ARTIFACT ""
ENV USERNAME ""
ENV PASSWORD ""
ENV NEXUS_URL ""
ENV REPO_NAME ""

ENV SLEEP_DURATION 5s
ENV ACTIVITY_SUB_TASK_CODE PUSH_ARTIFACT
ENV VALIDATION_FAILURE_ACTION WARNING

ENTRYPOINT [ "./build.sh" ]